services:
  rt-kas:
    build:
      context: .
      dockerfile: Dockerfile
    image: rt-kas:latest
    container_name: rt-kas
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "3030"
      HOSTNAME: 0.0.0.0
      NODE_OPTIONS: --max-old-space-size=512
      DATABASE_URL: ${DATABASE_URL:?DATABASE_URL is required}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET is required}
      BETTER_AUTH_URL: https://rt-kas.humalab.my.id/
      BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS:-${DOCKER_APP_URL:-http://localhost:3030}}
      REDIS_URL: redis://default:BwQEEo7wv6ztUqokRB7t@43.163.106.36:6379
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION:-1}
    ports:
      - "3030:3030"
    mem_limit: 768m
    memswap_limit: 768m
    networks:
      - dokploy-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:3030/api/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dokploy-network:
    external: true
